### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by Pheromon** [DEgITx/rats-search#145]
I leave my client running for days (I suppose this should be the default usage), but after a few hours I get out of heap memory errors.

Can you provide a way to configure the usage of bigger heaps?

**Comment by DEgITx** [comment]
can yo send rats.log?

**Comment by Pheromon** [comment]
Sorry I missed your request.
I tried to add --max-old-space-size=16000 to the node options and it worked for longer time, but at the end it crashed anyway and now it will not start anymore.

I can't find any rats.log file anywhere: do I need to enable debugging somewhere?

**Comment by DEgITx** [comment]
it's must be in the same folder where db and other config files, what OS do you using?

**Comment by Pheromon** [comment]
debian 11 (bullseye)

**Comment by Pheromon** [comment]
Anyway even if augmenting the memory size in that way seems to help , after a few days of running I still get plenty of errors and I need to restart the server.
Maybe I need to give more memory to sphinx or other background tools, too?

**Comment by Pheromon** [comment]
This issue is till marked with "waiting for reply", do you need more informations?

**Comment by DEgITx** [comment]
yes, if possible, when it's happens, and if possible attach rats.log, it's must be in Rats on the Boat folder, on unix systems somehre on ~/.config or ~/.share directories

**Comment by Pheromon** [comment]
There is no such file on my system, I found the directory you say:
/home/sw/.config/Rats on The Boat
but it has only an empty directory named "Dictionaries"

**Comment by DEgITx** [comment]
can you send which version of app you are running, web or GUI, 
the gui version folder must be there and have such struct

![image](https://user-images.githubusercontent.com/207785/125300591-dbc62d00-e332-11eb-8ea6-e5c26ddfedb7.png)

**Comment by Pheromon** [comment]
In the directory where I clone the repo and run th server (web version) I have some of the files you show here (for example version.vrs, sphinx.conf, query.og and searchd.log), but no rats.log.

**Comment by Pheromon** [comment]
BTW, I have no clue how to run the GUI version, you don't explain in the readme, and I'm interested

**Comment by DEgITx** [comment]
> n the directory where I clone the repo and run th server (web version) I have some of the files you show here (for example version.vrs, sphinx.conf, query.og and searchd.log), but no rats.log.

for web version it's in the same directory as sources

**Comment by DEgITx** [comment]
> BTW, I have no clue how to run the GUI version, you don't explain in the readme, and I'm interested

GUI version it's https://github.com/DEgITx/rats-search/releases/tag/v1.7.1 AppImage for example, as desktop application, not web one

**Comment by Pheromon** [comment]
This morning my instance was not working and on the console I had millions of lines like this one: I had to kill -9 the server to make it stop. A simple kill signal didn't work.

```
[replication] replicate remote torrent [H-Manga] COMIC Ananga Ranga Vol. 9 [Digital] - COMIC アナンガ・ランガvol.9 [DL版] [Japanese]
[add] Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (/home/dusty/rats-search/node_modules/mysql/lib/protocol/Protocol.js:212:16)
    at Protocol._enqueue (/home/dusty/rats-search/node_modules/mysql/lib/protocol/Protocol.js:138:13)
    at Connection.query (/home/dusty/rats-search/node_modules/mysql/lib/Connection.js:198:25)
    at queryCall (/home/dusty/rats-search/src/background/mysql.js:12:10)
    at /home/dusty/rats-search/src/background/mysql.js:30:4
    at new Promise (<anonymous>)
    at Connection.sphinx.query (/home/dusty/rats-search/src/background/mysql.js:15:42)
    at /home/dusty/rats-search/src/background/spider.js:622:17
    at new Promise (<anonymous>)
    at insertTorrentToDB (/home/dusty/rats-search/src/background/spider.js:543:50) {
  code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR',
  fatal: false
}
```

If it useful (I doubt) I'll open a separate issue, please tell me.

**Comment by DEgITx** [comment]
for each problem open separate, open and attach log

**Comment by Pheromon** [comment]
the problem btw is still I have no rats.log anywhere. 
I deleted the ".config/Rats on The Boat" directory and restarted the program, it didn't get recreated.

Any hint?

**Comment by DEgITx** [comment]
I already told that rats.log in the same folder with sources for web version

**Comment by DEgITx** [comment]
I will recheck this

**Comment by Pheromon** [comment]
I know, but the file doesn't exist anywhere and, believe me, I looked everywhere

so, how can I check why the file is not created?

**Comment by DEgITx** [comment]
this functionality was missing in web version, I restored in master

**Comment by Pheromon** [comment]
Can I run master or I risk losing the db again?

**Comment by DEgITx** [comment]
yes you can

**Comment by Pheromon** [comment]
So, I run master with 16GB of ram and everything went fine for a couple days but eventually started to get these errors:
```
[4:26:50 AM] Rejection: Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (/home/dusty/rats-search/node_modules/mysql/lib/protocol/Protocol.js:212:16)
    at Protocol._enqueue (/home/dusty/rats-search/node_modules/mysql/lib/protocol/Protocol.js:138:13)
    at Connection.query (/home/dusty/rats-search/node_modules/mysql/lib/Connection.js:198:25)
    at queryCall (/home/dusty/rats-search/src/background/mysql.js:12:10)
    at /home/dusty/rats-search/src/background/mysql.js:18:4
    at new Promise (<anonymous>)
    at Connection.sphinx.query (/home/dusty/rats-search/src/background/mysql.js:15:42)
    at buildPoolMethod (/home/dusty/rats-search/src/background/mysql.js:246:56)
    at Proxy.query (/home/dusty/rats-search/src/background/mysql.js:252:12)
    at topTorrentsCall (/home/dusty/rats-search/src/background/api.js:553:10) {
  code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR',
  fatal: false
}
```
And even pressing CTRl-C multiple times the server was unable to stop.

At the end I pressed CTRL-\ to kill it and was able to re-run the server.

I don't seem to find something interesting in the log file, do you want me to attach it?

**Comment by DEgITx** [comment]
please provide me also logs/screen of memory usage of rats processes after few days, also will help

**Comment by Pheromon** [comment]
Memory situation before today's crash
```
22174  0.0  0.0   2424   536 pts/5    S+   Jul23   0:00  |       \_ sh -c node --max-old-space-size=16000 src/background/server.js
22175  0.0 32.0 20572424 19756860 pts/5 Rl+ Jul23 3735:23  |           \_ node --max-old-space-size=16000 src/background/server.js
22229  0.0  6.2 7119344 3855224 pts/5 Sl+  Jul23 6887:09  |               \_ /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
```

**Comment by Pheromon** [comment]
today it crashed by itself and these are the latest rows on the console:
```
[tracker] found Nachalo.2010. BDRip.avi on rutracker
[system] Rejection: Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (/home/user/rats-search/node_modules/mysql/lib/protocol/Protocol.js:212:16)
    at Protocol._enqueue (/home/user/rats-search/node_modules/mysql/lib/protocol/Protocol.js:138:13)
    at Connection.query (/home/user/rats-search/node_modules/mysql/lib/Connection.js:198:25)                                                                                                                                                                          at queryCall (/home/user/rats-search/src/background/mysql.js:12:10)
    at /home/user/rats-search/src/background/mysql.js:18:4                                                                                                                                                                                                            at new Promise (<anonymous>)
    at Connection.sphinx.query (/home/user/rats-search/src/background/mysql.js:15:42)                                                                                                                                                                                 at Object.randomTorrents (/home/user/rats-search/src/background/api.js:221:17)
    at Socket.<anonymous> (/home/user/rats-search/src/background/p2p.js:96:40)                                                                                                                                                                                        at Socket.emit (node:events:394:28) {
  code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR',
  fatal: false
}                                                                                                                                                                                                                                                                  

<--- Last few GCs --->                                                                                                                                                                                                                                             
[22446:0x6652f60] 256979190 ms: Scavenge (reduce) 15603.5 (16043.0) -> 15603.1 (16043.0) MB, 44.9 / 0.0 ms  (average mu = 0.385, current mu = 0.384) allocation failure
[22446:0x6652f60] 256979242 ms: Scavenge (reduce) 15603.7 (16043.6) -> 15603.4 (16043.4) MB, 43.7 / 0.0 ms  (average mu = 0.385, current mu = 0.384) allocation failure
[22446:0x6652f60] 256979375 ms: Scavenge (reduce) 15605.1 (16044.2) -> 15604.4 (16044.2) MB, 47.9 / 0.0 ms  (average mu = 0.385, current mu = 0.384) allocation failure


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb17ec0 node::Abort() [node]
 2: 0xa341f4 node::FatalError(char const*, char const*) [node]
 3: 0xcfe71e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xcfea97 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xee8d35  [node]
 6: 0xee987c  [node]
 7: 0xef77b1 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 8: 0xefad0c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 9: 0xebebb5 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node]
10: 0xeb9a59 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [node]
11: 0xeb9b14 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [node]
12: 0x110269d v8::internal::Handle<v8::internal::NameDictionary> v8::internal::HashTable<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::New<v8::internal::Isolate>(v8::internal::Isolate*, int, v8::internal::AllocationType, v8::internal::Mini
mumCapacity) [node]
13: 0x11028d3 v8::internal::Handle<v8::internal::NameDictionary> v8::internal::HashTable<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::EnsureCapacity<v8::internal::Isolate>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::NameDic
tionary>, int, v8::internal::AllocationType) [node]
14: 0x1102e96 v8::internal::Handle<v8::internal::NameDictionary> v8::internal::Dictionary<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::Add<v8::internal::Isolate>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::NameDictionary>,
v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyDetails, v8::internal::InternalIndex*) [node]
15: 0x110665a v8::internal::BaseNameDictionary<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::Add(v8::internal::Isolate*, v8::internal::Handle<v8::internal::NameDictionary>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8:
:internal::Object>, v8::internal::PropertyDetails, v8::internal::InternalIndex*) [node]
16: 0x10d5989 v8::internal::LookupIterator::ApplyTransitionToDataProperty(v8::internal::Handle<v8::internal::JSReceiver>) [node]
17: 0x10f4003 v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::Maybe<v8::internal::ShouldThrow>, v8::internal::StoreOrigin) [node]
18: 0x10abdd9 v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::Maybe<v8::internal::ShouldThrow>, v8::internal::JSObject::AccessorInfoHand
ling) [node]
19: 0x10ac0f9 v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::JSObject::AccessorInfoHandling) [node]
20: 0xfdf18a v8::internal::JsonParser<unsigned char>::BuildJsonObject(v8::internal::JsonParser<unsigned char>::JsonContinuation const&, std::vector<v8::internal::JsonProperty, std::allocator<v8::internal::JsonProperty> > const&, v8::internal::Handle<v8::inter
nal::Map>) [node]
21: 0xfe0729 v8::internal::JsonParser<unsigned char>::ParseJsonValue() [node]
22: 0xfe15ef v8::internal::JsonParser<unsigned char>::ParseJson() [node]
23: 0xda3638  [node]
24: 0xda3c06 v8::internal::Builtin_JsonParse(int, unsigned long*, v8::internal::Isolate*) [node]
25: 0x16148d9  [node]
Aborted
```

**Comment by Pheromon** [comment]
BTW, the issues is still marked with "awaiting reply", may I give you more informations?

**Comment by DEgITx** [comment]
if possible also make screen of htop after few days of usage and attach here

**Comment by Pheromon** [comment]
I will collect the relevant statistics of the process, in the meantime version 1.8 after a few days of great working crashed in this way:
```
<--- Last few GCs --->

[7687:0x5318f60] 292367133 ms: Scavenge 16029.4 (16511.9) -> 16027.9 (16510.6) MB, 78.5 / 0.0 ms  (average mu = 0.624, current mu = 0.000) allocation failure
[7687:0x5318f60] 292367331 ms: Scavenge 16037.1 (16516.3) -> 16035.3 (16516.3) MB, 56.2 / 0.1 ms  (average mu = 0.624, current mu = 0.000) allocation failure
[7687:0x5318f60] 292367401 ms: Scavenge 16035.3 (16516.3) -> 16035.2 (16516.3) MB, 70.3 / 0.0 ms  (average mu = 0.624, current mu = 0.000) allocation failure


<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 0xb17ec0 node::Abort() [node]
 2: 0xa341f4 node::FatalError(char const*, char const*) [node]
 3: 0xcfe71e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xcfea97 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xee8d35  [node]
 6: 0xf16858 v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [node]
 7: 0xf21bfe v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [node]
 8: 0xf10edf v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [node]
 9: 0xf1120f v8::internal::PageEvacuationJob::Run(v8::JobDelegate*) [node]
10: 0x18fedf4 v8::platform::DefaultJobWorker::Run() [node]
11: 0xb83345  [node]
12: 0x7fa05b72fea7  [/lib/x86_64-linux-gnu/libpthread.so.0]
13: 0x7fa05b65fdef clone [/lib/x86_64-linux-gnu/libc.so.6]
Aborted
```

**Comment by Pheromon** [comment]
This a part of the htop situation after a couple days
```
  PID USER      PRI  NI  VIRT   RES   SHR S CPU%▽MEM%   TIME+  Command 
28454 user      20   0 3930M 3230M 2680M S 472.  5.4     515h /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
28463 user      20   0 3930M 3230M 2680M S 75.8  5.4 51h19:47 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
 9007 user      20   0 12.7G 11.9G 40584 S 72.2 19.8 21h33:49 node --max-old-space-size=26000 src/background/server.js
28462 user      20   0 3930M 3230M 2680M S 61.4  5.4 51h18:23 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
28458 user      20   0 3930M 3230M 2680M S 50.5  5.4 51h17:55 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
28459 user      20   0 3930M 3230M 2680M S 50.5  5.4 51h21:08 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
28461 user      20   0 3930M 3230M 2680M S 46.9  5.4 51h18:06 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
28456 user      20   0 3930M 3230M 2680M S 43.3  5.4 51h19:05 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
28457 user      20   0 3930M 3230M 2680M R 43.3  5.4 51h18:38 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
28455 user      20   0 3930M 3230M 2680M S 39.7  5.4 51h18:25 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
28464 user      20   0 3930M 3230M 2680M S 32.5  5.4 51h21:25 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
28460 user      20   0 3930M 3230M 2680M R 25.3  5.4 51h19:22 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
```

**Comment by Pheromon** [comment]
htop dump a day later: as you can see the used memory grows until it reaches the maximum allowed
```
28454 user      20   0 4082M 3341M 2780M S 198.  5.5     582h /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
 9007 user      20   0 18.7G 17.9G 40584 R 95.5 29.8 41h54:03 node --max-old-space-size=26000 src/background/server.js
28461 user      20   0 4082M 3341M 2780M S 18.1  5.5 57h56:13 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
28456 user      20   0 4082M 3341M 2780M S 21.3  5.5 57h58:13 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
28459 user      20   0 4082M 3341M 2780M S 18.7  5.5 57h59:40 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
28464 user      20   0 4082M 3341M 2780M R 29.0  5.5 58h00:32 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
28462 user      20   0 4082M 3341M 2780M S 18.7  5.5 57h57:10 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
28463 user      20   0 4082M 3341M 2780M S 15.5  5.5 57h58:42 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
28457 user      20   0 4082M 3341M 2780M S 17.4  5.5 57h57:03 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
28455 user      20   0 4082M 3341M 2780M S 16.8  5.5 57h57:03 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
28458 user      20   0 4082M 3341M 2780M S 21.9  5.5 57h56:42 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
28460 user      20   0 4082M 3341M 2780M S 20.6  5.5 57h58:13 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
 9009 user      20   0 18.7G 17.9G 40584 S  0.6 29.8 26:43.55 node --max-old-space-size=26000 src/background/server.js
 9011 user      20   0 18.7G 17.9G 40584 S  0.0 29.8 26:57.65 node --max-old-space-size=26000 src/background/server.js
 9010 user      20   0 18.7G 17.9G 40584 S  0.0 29.8 26:55.70 node --max-old-space-size=26000 src/background/server.js
 9012 user      20   0 18.7G 17.9G 40584 S  1.3 29.8 27:05.50 node --max-old-space-size=26000 src/background/server.js
 3419 user      20   0 4082M 3341M 2780M S  0.6  5.5  2h26:56 /home/user/rats-search/imports/linux/x64/searchd --config /home/user/rats-search/sphinx.conf --nodetach
 9056 user      20   0 18.7G 17.9G 40584 S  0.0 29.8  4:38.06 node --max-old-space-size=26000 src/background/server.js
 ```
