### ISSUE TITLE
Various errors from the log

### ISSUE THREAD

**Issue by Pheromon** [DEgITx/rats-search#150]
Now that I have a rats.log file :-) I took a look at it and I found a few errors here and there, I put them here to not be lost, hoping they are useful.

I'm running master

```
[6:42:12 AM] Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (/home/dusty/rats-search/node_modules/mysql/lib/protocol/Protocol.js:212:16)
    at Protocol._enqueue (/home/dusty/rats-search/node_modules/mysql/lib/protocol/Protocol.js:138:13)
    at Connection.query (/home/dusty/rats-search/node_modules/mysql/lib/Connection.js:198:25)
    at queryCall (/home/dusty/rats-search/src/background/mysql.js:12:10)
    at /home/dusty/rats-search/src/background/mysql.js:30:4
    at new Promise (<anonymous>)
    at Connection.sphinx.query (/home/dusty/rats-search/src/background/mysql.js:15:42)
    at buildPoolMethod (/home/dusty/rats-search/src/background/mysql.js:246:56)
    at Proxy.query (/home/dusty/rats-search/src/background/mysql.js:252:12)
    at searchFilesCall (/home/dusty/rats-search/src/background/api.js:437:10) {
  code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR',
  fatal: false
}
```
^^ This one is the most recurring one

```
[6:42:09 AM] Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Torrent`. See https://reactjs.org/link/warning-keys for more information.
span
Torrent@webpack://rats-search/./src/app/torrent.js?:142:5
div
List@webpack://rats-search/./node_modules/material-ui/List/List.js?:57:34
SearchResults@webpack://rats-search/./src/app/search-results.js?:17:1
div
div
SearchPage@webpack://rats-search/./src/app/search-page.js?:22:5
div
Singleton@webpack://rats-search/./src/app/singleton.js?:9:7
div
MuiThemeProvider@webpack://rats-search/./node_modules/material-ui/styles/MuiThemeProvider.js?:43:34
App@webpack://rats-search/./src/app/app.js?:97:5 null
```

```
[6:42:03 AM] Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
a
div
__WEBPACK_DEFAULT_EXPORT__@webpack://rats-search/./src/app/trackers-images.js?:15:7
div
a
div
div
TouchRipple@webpack://rats-search/./node_modules/material-ui/internal/TouchRipple.js?:77:34
span
EnhancedButton@webpack://rats-search/./node_modules/material-ui/internal/EnhancedButton.js?:97:34
div
ListItem@webpack://rats-search/./node_modules/material-ui/List/ListItem.js?:219:34
div
Torrent@webpack://rats-search/./src/app/torrent.js?:142:5
div
List@webpack://rats-search/./node_modules/material-ui/List/List.js?:57:34
RecentTorrents@webpack://rats-search/./src/app/feed.js?:19:5
div
div
FeedPage@webpack://rats-search/./src/app/feed-page.js?:15:5
div
Singleton@webpack://rats-search/./src/app/singleton.js?:9:7
div
MuiThemeProvider@webpack://rats-search/./node_modules/material-ui/styles/MuiThemeProvider.js?:43:34
App@webpack://rats-search/./src/app/app.js?:97:5 null
```

**Comment by DEgITx** [comment]
2,3 errors not intresting one - it's ok, only first one related, can you attach full log?

**Comment by Pheromon** [comment]
Full log attached
[rats.log.gz](https://github.com/DEgITx/rats-search/files/6817318/rats.log.gz)
