### ISSUE TITLE
Server installation issue

### ISSUE THREAD

**Issue by kalgurn** [DEgITx/rats-search#29]
rats-search - v0.19.1
OS: Alpine
During the `npm install` there is an issue with prebuilt dependencies:
```
> prebuild-install || node-gyp rebuild
prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/bufferutil-v3.0.4-node-v57-linuxmusl-x64.tar.gz
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/https-github.com-websockets-bufferutil-releases-download-v3.0.4-bufferutil-v3.0.4-node-v57-linuxmusl-x64.tar.gz
prebuild-install http request GET https://github.com/websockets/bufferutil/releases/download/v3.0.4/bufferutil-v3.0.4-node-v57-linuxmusl-x64.tar.gz
prebuild-install http 404 https://github.com/websockets/bufferutil/releases/download/v3.0.4/bufferutil-v3.0.4-node-v57-linuxmusl-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=8.9.3 runtime=node arch=x64 platform=linux)
```

Perhaps [links](https://github.com/websockets/bufferutil/releases/tag/v3.0.4) have changed? 
WARNs with some dependencies:

```
npm WARN lifecycle rats-search@0.19.0~postinstall: cannot run in wd %s %s (wd=%s) rats-search@0.19.0 electron-builder install-app-deps /rats-search
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-win@1.8.6 (node_modules/app-builder-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-win@1.8.6: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-mac@1.8.6 (node_modules/app-builder-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-mac@1.8.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.2.0 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.2.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

`npm run server` log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'server' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose run-script [ 'preserver', 'server', 'postserver' ]
5 info lifecycle rats-search@0.19.0~preserver: rats-search@0.19.0
6 info lifecycle rats-search@0.19.0~server: rats-search@0.19.0
7 verbose lifecycle rats-search@0.19.0~server: unsafe-perm in lifecycle true
8 verbose lifecycle rats-search@0.19.0~server: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/rats-s
earch/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle rats-search@0.19.0~server: CWD: /rats-search
10 silly lifecycle rats-search@0.19.0~server: Args: [ '-c', 'node src/background/server.js' ]
11 silly lifecycle rats-search@0.19.0~server: Returned: code: 1  signal: null
12 info lifecycle rats-search@0.19.0~server: Failed to exec server script
13 verbose stack Error: rats-search@0.19.0 server: `node src/background/server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/
index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/
lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid rats-search@0.19.0
15 verbose cwd /rats-search
16 verbose Linux 4.4.111-boot2docker
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "server"
18 verbose node v8.9.3
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error rats-search@0.19.0 server: `node src/background/server.js`
22 error Exit status 1
23 error Failed at the rats-search@0.19.0 server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by DEgITx** [comment]
this is probably npm install error, can you give full log of it, or this is full one?
and what exact Alpine version it is?

`

**Comment by DEgITx** [comment]
i hope you are using x64 version of alpine, replace this component in imports/linux/x64 directory and update version from last with git
[alpine_x64_searchd.tar.gz](https://github.com/DEgITx/rats-search/files/1972698/alpine_x64_searchd.tar.gz)

**Comment by DEgITx** [comment]
https://github.com/DEgITx/rats-search/blob/master/docs/SERVER_COMPATIBILITY.md

**Comment by DEgITx** [comment]
fix documented in 0.19.2
