### ISSUE TITLE
Craching of application in service mode

### ISSUE THREAD

**Issue by CanisMorr** [DEgITx/rats-search#30]
Application that runs as a service, crashes after a few hours.

OS information:
```
root@canis2:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
root@canis2:~# uname -a
Linux canis2 4.4.0-122-generic #146-Ubuntu SMP Mon Apr 23 15:34:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@canis2:~# node --version
v7.10.1
root@canis2:~# npm --version
4.2.0
```

Standard output from application while crash:
```
replicate remote torrent Trinoline -Soundtrack Bonus  NOT INCLUDED
replicate remote torrent Пицца - 2 альбома (FLAC)
finded torrent Oruna, Maria - Puerto escondido [25748] (r1.1).epub  and add to database
buffer.js:805
        return this.hexWrite(string, offset, length);
                    ^
 
TypeError: Invalid hex string
    at Buffer.write (buffer.js:805:21)
    at scrapeTorrent (/home/canis/rats-search/src/background/bt/udp-tracker-request.js:61:12)
    at Socket.<anonymous> (/home/canis/rats-search/src/background/bt/udp-tracker-request.js:85:9)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:194:7)
    at UDP.onMessage [as onmessage] (dgram.js:544:8)
 
npm ERR! Linux 4.4.0-122-generic
npm ERR! argv "/home/canis/.nvm/versions/node/v7.10.1/bin/node" "/home/canis/.nvm/versions/node/v7.10.1/bin/npm" "run" "server"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rats-search@0.19.1 server: `node src/background/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rats-search@0.19.1 server script 'node src/background/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rats-search package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node src/background/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rats-search
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rats-search
npm ERR! There is likely additional logging output above.
 
npm ERR! Please include the following file with any support request:
npm ERR!     /home/canis/.npm/_logs/2018-05-04T10_32_36_145Z-debug.log
```
/home/canis/.npm/_logs/2018-05-04T10_32_36_145Z-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/canis/.nvm/versions/node/v7.10.1/bin/node',
1 verbose cli   '/home/canis/.nvm/versions/node/v7.10.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'server' ]
2 info using npm@4.2.0
3 info using node@v7.10.1
4 verbose run-script [ 'preserver', 'server', 'postserver' ]
5 info lifecycle rats-search@0.19.1~preserver: rats-search@0.19.1
6 silly lifecycle rats-search@0.19.1~preserver: no script for preserver, continuing
7 info lifecycle rats-search@0.19.1~server: rats-search@0.19.1
8 verbose lifecycle rats-search@0.19.1~server: unsafe-perm in lifecycle true
9 verbose lifecycle rats-search@0.19.1~server: PATH: /home/canis/.nvm/versions/node/v7.10.1/lib/node_modules/npm/bin/node-gyp-bin:/home/canis/rats-search/node_modules/.bin:/home/canis/.nvm/versions/node/v7.10.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle rats-search@0.19.1~server: CWD: /home/canis/rats-search
11 silly lifecycle rats-search@0.19.1~server: Args: [ '-c', 'node src/background/server.js' ]
12 silly lifecycle rats-search@0.19.1~server: Returned: code: 1  signal: null
13 info lifecycle rats-search@0.19.1~server: Failed to exec server script
14 verbose stack Error: rats-search@0.19.1 server: `node src/background/server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/canis/.nvm/versions/node/v7.10.1/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/canis/.nvm/versions/node/v7.10.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid rats-search@0.19.1
16 verbose cwd /home/canis/rats-search
17 error Linux 4.4.0-122-generic
18 error argv "/home/canis/.nvm/versions/node/v7.10.1/bin/node" "/home/canis/.nvm/versions/node/v7.10.1/bin/npm" "run" "server"
19 error node v7.10.1
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error rats-search@0.19.1 server: `node src/background/server.js`
23 error Exit status 1
24 error Failed at the rats-search@0.19.1 server script 'node src/background/server.js'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the rats-search package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     node src/background/server.js
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs rats-search
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls rats-search
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

```

**Comment by DEgITx** [comment]
Must be fixed in 0.19.2
