### ISSUE TITLE
Segmentation fault on service mode

### ISSUE THREAD

**Issue by CanisMorr** [DEgITx/rats-search#31]
Got segmentation fault on service mode.

OS information:
```
root@canis2:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
root@canis2:~# uname -a
Linux canis2 4.4.0-122-generic #146-Ubuntu SMP Mon Apr 23 15:34:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@canis2:~# node --version
v7.10.1
root@canis2:~# npm --version
4.2.0
```

Standard output from application while crash:
```
{ hash: 'f9413e3349a64227548bf7275087211ed5fb470c',
  path: 'Shadowhunters S01E11 Blood Calls to Blood.mp4',
  size: 253744974,
  id: 4354294,
  pathIndex: 'Shadowhunters S01E11 Blood Calls to Blood.mp4' }
{ Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/canis/rats-search/node_modules/mysql/lib/protocol/Protocol.js:113:13)
    at Socket.<anonymous> (/home/canis/rats-search/node_modules/mysql/lib/Connection.js:109:28)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    --------------------
    at Protocol._enqueue (/home/canis/rats-search/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/home/canis/rats-search/node_modules/mysql/lib/Connection.js:208:25)
    at Promise (/home/canis/rats-search/src/background/mysql.js:22:13)
    at Connection.sphinx.query (/home/canis/rats-search/src/background/mysql.js:7:45)
    at insertTorrentToDB (/home/canis/rats-search/src/background/spider.js:431:14)
    at updateTorrent (/home/canis/rats-search/src/background/spider.js:552:2)
    at Client.<anonymous> (/home/canis/rats-search/src/background/spider.js:582:3)
    at emitThree (events.js:116:13)
    at Client.emit (events.js:197:7)
    at Wire.wire.on (/home/canis/rats-search/src/background/bt/client.js:61:22) fatal: true, code: 'PROTOCOL_CONNECTION_LOST' }
{ hash: 'd443b5186c66b9442062394a125edf91a7b51b0d',
  name: 'Nero.Burning.Rom.11.2011.PC',
  size: 124104850,
  files: 2,
  piecelength: 131072,
  ipv4: '73.166.175.208',
  port: 36575,
  added: 1525532241,
  contentType: 'application',
  id: 254195,
  nameIndex: 'Nero.Burning.Rom.11.2011.PC' }
{ Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/canis/rats-search/node_modules/mysql/lib/protocol/Protocol.js:113:13)
    at Socket.<anonymous> (/home/canis/rats-search/node_modules/mysql/lib/Connection.js:109:28)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    --------------------
    at Protocol._enqueue (/home/canis/rats-search/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/home/canis/rats-search/node_modules/mysql/lib/Connection.js:208:25)
    at Promise (/home/canis/rats-search/src/background/mysql.js:22:13)
    at Connection.sphinx.query (/home/canis/rats-search/src/background/mysql.js:7:45)
    at insertTorrentToDB (/home/canis/rats-search/src/background/spider.js:431:14)
    at updateTorrent (/home/canis/rats-search/src/background/spider.js:552:2)
    at Client.<anonymous> (/home/canis/rats-search/src/background/spider.js:582:3)
    at emitThree (events.js:116:13)
    at Client.emit (events.js:197:7)
    at Wire.wire.on (/home/canis/rats-search/src/background/bt/client.js:61:22) fatal: true, code: 'PROTOCOL_CONNECTION_LOST' }
Segmentation fault

npm ERR! Linux 4.4.0-122-generic
npm ERR! argv "/home/canis/.nvm/versions/node/v7.10.1/bin/node" "/home/canis/.nvm/versions/node/v7.10.1/bin/npm" "run" "server"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 139
npm ERR! rats-search@0.19.2 server: `node src/background/server.js`
npm ERR! Exit status 139
npm ERR!
npm ERR! Failed at the rats-search@0.19.2 server script 'node src/background/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rats-search package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node src/background/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rats-search
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rats-search
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/canis/.npm/_logs/2018-05-05T16_47_40_260Z-debug.log
```

/home/canis/.npm/_logs/2018-05-05T16_47_40_260Z-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/canis/.nvm/versions/node/v7.10.1/bin/node',
1 verbose cli   '/home/canis/.nvm/versions/node/v7.10.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'server' ]
2 info using npm@4.2.0
3 info using node@v7.10.1
4 verbose run-script [ 'preserver', 'server', 'postserver' ]
5 info lifecycle rats-search@0.19.2~preserver: rats-search@0.19.2
6 silly lifecycle rats-search@0.19.2~preserver: no script for preserver, continuing
7 info lifecycle rats-search@0.19.2~server: rats-search@0.19.2
8 verbose lifecycle rats-search@0.19.2~server: unsafe-perm in lifecycle true
9 verbose lifecycle rats-search@0.19.2~server: PATH: /home/canis/.nvm/versions/node/v7.10.1/lib/node_modules/npm/bin/node-gyp-bin:/home/canis/rats-search/node_modules/.bin:/home/canis/.nvm/versions/node/v7.10.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle rats-search@0.19.2~server: CWD: /home/canis/rats-search
11 silly lifecycle rats-search@0.19.2~server: Args: [ '-c', 'node src/background/server.js' ]
12 silly lifecycle rats-search@0.19.2~server: Returned: code: 139  signal: null
13 info lifecycle rats-search@0.19.2~server: Failed to exec server script
14 verbose stack Error: rats-search@0.19.2 server: `node src/background/server.js`
14 verbose stack Exit status 139
14 verbose stack     at EventEmitter.<anonymous> (/home/canis/.nvm/versions/node/v7.10.1/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/canis/.nvm/versions/node/v7.10.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid rats-search@0.19.2
16 verbose cwd /home/canis/rats-search
17 error Linux 4.4.0-122-generic
18 error argv "/home/canis/.nvm/versions/node/v7.10.1/bin/node" "/home/canis/.nvm/versions/node/v7.10.1/bin/npm" "run" "server"
19 error node v7.10.1
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 139
23 error rats-search@0.19.2 server: `node src/background/server.js`
23 error Exit status 139
24 error Failed at the rats-search@0.19.2 server script 'node src/background/server.js'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the rats-search package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     node src/background/server.js
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs rats-search
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls rats-search
24 error There is likely additional logging output above.
25 verbose exit [ 139, true ]
```

**Comment by CanisMorr** [comment]
Standard output beginning with repetitive errors:
```
close peer connection { address: '95.30.223.62', port: 4445 }
close peer connection { address: '78.25.169.195', port: 52130 }
finded torrent Знакомый трахает свою жену 8_(domaha.tv).mpg  and add to database
finded torrent Wildling.2018.720p.WEBRip.HiWayGrope.mkv  and add to database
sphinx: last message repeated 1 times
caught SIGTERM, shutting down

{ files: 3,
  piecelength: 1048576,
  port: 46355,
  seeders: 0,
  leechers: 1,
  completed: 0,
  good: 0,
  bad: 0,
  size: 826087006,
  added: 1517627289,
  trackerschecked: 1523861164,
  hash: 'cf08457e0b7286029c9f62c6fd2d523a48b4beb5',
  name: 'BackRoomMilf - Violet Marcelle',
  ipv4: '37.11.134.189',
  contentcategory: null,
  contentType: 'video',
  id: 144313,
  nameIndex: 'BackRoomMilf - Violet Marcelle' }
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
    --------------------
    at Protocol._enqueue (/home/canis/rats-search/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/home/canis/rats-search/node_modules/mysql/lib/Connection.js:208:25)
    at Promise (/home/canis/rats-search/src/background/mysql.js:48:3)
    at Connection.sphinx.insertValues (/home/canis/rats-search/src/background/mysql.js:34:56)
    at mysqlSingle.query (/home/canis/rats-search/src/background/spider.js:445:15)
    at Query.queryCall [as _callback] (/home/canis/rats-search/src/background/mysql.js:29:21)
    at Query.Sequence.end (/home/canis/rats-search/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query._handleFinalResultPacket (/home/canis/rats-search/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.EofPacket (/home/canis/rats-search/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
    at Protocol._parsePacket (/home/canis/rats-search/node_modules/mysql/lib/protocol/Protocol.js:279:23)
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  fatal: true }
```

**Comment by DEgITx** [comment]
must be fixed some commits ago, if the problem still exists create new ticket with new log
