### ISSUE TITLE
Server version build problems

### ISSUE THREAD

**Issue by rusmonkey** [DEgITx/rats-search#33]
ubuntu server 17.10
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN babel-loader@8.0.0-beta.3 requires a peer of @babel/core@^7.0.0 || ^7.0.0-rc || ^7.0.0-beta.41 but none was installed.
npm WARN @semantic-release/changelog@1.1.1 requires a peer of semantic-release@>=13.3.0 <15.0.0 but none was installed.
npm WARN @semantic-release/exec@2.2.4 requires a peer of semantic-release@>=13.0.0 <16.0.0 but none was installed.
npm WARN @semantic-release/git@3.1.1 requires a peer of semantic-release@>=13.3.0 <15.0.0 but none was installed.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none was installed.

compilation errors [ ModuleBuildError: Module build failed: Error: babel-loader ^8.0.0-beta.3 requires @babel/core@7.0.0-beta.41, but you appear to be using "7.0.0-beta.38". Either update your @babel/core version, or pin you babel-loader version to 8.0.0-beta.2
      at Object.<anonymous> (/home/userName/down/rats-search/node_modules/babel-loader/lib/index.js:79:13)
      at next (native)
      at step (/home/userName/down/rats-search/node_modules/babel-loader/lib/index.js:3:221)
      at _next (/home/userName/down/rats-search/node_modules/babel-loader/lib/index.js:3:409)
      at /home/userName/down/rats-search/node_modules/babel-loader/lib/index.js:3:477
      at Object.<anonymous> (/home/userName/down/rats-search/node_modules/babel-loader/lib/index.js:3:97)
      at Object._loader (/home/userName/down/rats-search/node_modules/babel-loader/lib/index.js:148:18)
      at Object.loader (/home/userName/down/rats-search/node_modules/babel-loader/lib/index.js:36:18)
      at Object.<anonymous> (/home/userName/down/rats-search/node_modules/babel-loader/lib/index.js:31:12)
      at runLoaders (/home/userName/down/rats-search/node_modules/webpack/lib/NormalModule.js:252:20)
      at /home/userName/down/rats-search/node_modules/loader-runner/lib/LoaderRunner.js:364:11
      at /home/userName/down/rats-search/node_modules/loader-runner/lib/LoaderRunner.js:230:18
      at context.callback (/home/userName/down/rats-search/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
      at loader.call.then.err (/home/userName/down/rats-search/node_modules/babel-loader/lib/index.js:31:103)
      at runMicrotasksCallback (internal/process/next_tick.js:64:5)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9) ]

**Comment by DEgITx** [comment]
what npm version it is?
do you try update npm to last and try again
`npm install -g npm`

**Comment by rusmonkey** [comment]
i've updated npm and everything as before 

```
npm --version
3.5.2
```
```
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.10"
VERSION_ID="17.10"
```

npm WARN lifecycle rats-search@0.20.1~postinstall: cannot run in wd %s %s (wd=%s             ) rats-search@0.20.1 electron-builder install-app-deps /home/odm3n/down/rats-sea             rch
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve             nts@1.2.4
npm WARN @semantic-release/changelog@1.1.1 requires a peer of semantic-release@>             =13.3.0 <15.0.0 but none was installed.
npm WARN @semantic-release/exec@2.2.4 requires a peer of semantic-release@>=13.0             .0 <16.0.0 but none was installed.
npm WARN @semantic-release/git@3.1.1 requires a peer of semantic-release@>=13.3.             0 <15.0.0 but none was installed.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none was installed             .
npm WARN babel-loader@8.0.0-beta.3 requires a peer of @babel/core@^7.0.0 || ^7.0             .0-rc || ^7.0.0-beta.41 but none was installed.

**Comment by DEgITx** [comment]
try again from master, may be fixed

**Comment by rusmonkey** [comment]
```
root@UbuntuSrv:~/down/rats-search# npm install

> bufferutil@3.0.5 install /home/userName/down/rats-search/node_modules/bufferutil
> prebuild-install || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, mkdir '/home/userName/down                                                                                                                                                      /rats-search/node_modules/bufferutil/build'
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/userName/down/rats-se                                                                                                                                                      arch/node_modules/bufferutil/build'
gyp ERR! stack     at Error (native)
gyp ERR! System Linux 4.13.0-41-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/n                                                                                                                                                      ode-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/userName/down/rats-search/node_modules/bufferutil
gyp ERR! node -v v6.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> electron-chromedriver@1.8.0 install /home/userName/down/rats-search/node_modules/                                                                                                                                                      electron-chromedriver
> node ./download-chromedriver.js

/home/userName/down/rats-search/node_modules/electron-chromedriver/download-chromed                                                                                                                                                      river.js:32
    if (error != null) throw error
                       ^

Error: EACCES: permission denied, mkdir '/home/userName/down/rats-search/node_modul                                                                                                                                                      es/electron-chromedriver/bin'
    at Error (native)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fse                                                                                                                                                      vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                                                                                                      1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}                                                                                                                                                      )
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-win@1.8.6 (node_                                                                                                                                                      modules/app-builder-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-build                                                                                                                                                      er-bin-win@1.8.6: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","ar                                                                                                                                                      ch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-mac@1.8.6 (node_                                                                                                                                                      modules/app-builder-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-build                                                                                                                                                      er-bin-mac@1.8.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","a                                                                                                                                                      rch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.2.0 (node_modules                                                                                                                                                      /7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-                                                                                                                                                      win@2.2.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x6                                                                                                                                                      4"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules                                                                                                                                                      /7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-                                                                                                                                                      mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x                                                                                                                                                      64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@3.0.5 (node_modules/b                                                                                                                                                      ufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@3.0.5 install: `prebu                                                                                                                                                      ild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-chromedriver@1.8.0 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-chromedriver@1.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                                                                      ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/userName/.npm/_logs/2018-05-29T16_39_20_942Z-debug.log
[2018-05-29T16_39_20_942Z-debug.log](https://github.com/DEgITx/rats-search/files/2049305/2018-05-29T16_39_20_942Z-debug.log)

```

**Comment by DEgITx** [comment]
looks like problems with permission to directories inside /home/userName/down/rats-search , please check access in your system
