### ISSUE TITLE
debian 9 appimage issue

### ISSUE THREAD

**Issue by rahs** [DEgITx/rats-search#35]
4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

```./rats-search-0.21.1-x86_64.AppImage

(rats-search:17296): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(rats-search:17296): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(rats-search:17296): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_rats-ssJ4aD7/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
````

**Comment by DEgITx** [comment]
will be fixed in 0.22.0
