### ISSUE TITLE
Windows 10, JavaScrips Error

### ISSUE THREAD

**Issue by DjKamaL** [DEgITx/rats-search#37]
![screenshot_1](https://user-images.githubusercontent.com/19556974/41777419-ee3bcdc4-7633-11e8-8c29-2169be5ec9d2.png)

**Comment by DEgITx** [comment]
any details about reproduction? may be some info about case when it appear?

**Comment by DjKamaL** [comment]
Программа работала в фоне, скачивалась база торентов (ПК не был нагружен, и был по большому счету в простое длительное время).
После нескольких часов работы программы, по приходу домой, обнаружил данную ошибку.
(P.S. i7 4770K, 16GB RAM, GTX 1060, SSD)

Возможно при сбое программа сохраняет логи? Я бы прислал дополнительную информацию.

**Comment by DEgITx** [comment]
Rats.log в appdata, но он очищается при каждом старте

**Comment by DjKamaL** [comment]
В какой то момент зависла программа, решил посмотреть логи пока не закрывать процесс.
Вот что получилось (логов на 134МБ), прислал часть из конца лога.

`(C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:450:39)
    at L (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:619:10)
    at e.exports.<anonymous> (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:648:72)
    at emitThree (events.js:136:13)
    at e.exports.emit (events.js:217:7)
    at u.o.on (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\bt\client.js:72:13)
    at emitTwo (events.js:126:13)
    at u.emit (events.js:214:7) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
[2:35:27 PM] Rejection: { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:201:16)
    at Protocol._enqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:139:13)
    at Connection.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\Connection.js:208:25)
    at Promise (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:36:14)
    at new Promise (<anonymous>)
    at Connection.e.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:22:19)
    at n (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:518:9)
    at new Promise (<anonymous>)
    at z (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:450:39)
    at L (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:619:10)
    at e.exports.<anonymous> (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:648:72)
    at emitThree (events.js:136:13)
    at e.exports.emit (events.js:217:7)
    at u.o.on (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\bt\client.js:72:13)
    at emitTwo (events.js:126:13)
    at u.emit (events.js:214:7) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
[2:35:28 PM] finded torrent MUM229AVI  and add to database
[2:35:28 PM] { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:201:16)
    at Protocol._enqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:139:13)
    at Connection.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\Connection.js:208:25)
    at Promise (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:36:14)
    at new Promise (<anonymous>)
    at Connection.e.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:22:19)
    at n (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:480:18)
    at new Promise (<anonymous>)
    at z (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:450:39)
    at L (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:619:10)
    at e.exports.<anonymous> (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:648:72)
    at emitThree (events.js:136:13)
    at e.exports.emit (events.js:217:7)
    at u.o.on (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\bt\client.js:72:13)
    at emitTwo (events.js:126:13)
    at u.emit (events.js:214:7) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
[2:35:28 PM] Rejection: { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:201:16)
    at Protocol._enqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:139:13)
    at Connection.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\Connection.js:208:25)
    at Promise (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:36:14)
    at new Promise (<anonymous>)
    at Connection.e.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:22:19)
    at n (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:480:18)
    at new Promise (<anonymous>)
    at z (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:450:39)
    at L (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:619:10)
    at e.exports.<anonymous> (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:648:72)
    at emitThree (events.js:136:13)
    at e.exports.emit (events.js:217:7)
    at u.o.on (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\bt\client.js:72:13)
    at emitTwo (events.js:126:13)
    at u.emit (events.js:214:7) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
[2:35:28 PM] Rejection: { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:201:16)
    at Protocol._enqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:139:13)
    at Connection.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\Connection.js:208:25)
    at Promise (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:36:14)
    at new Promise (<anonymous>)
    at Connection.e.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:22:19)
    at n (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:518:9)
    at new Promise (<anonymous>)
    at z (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:450:39)
    at L (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:619:10)
    at e.exports.<anonymous> (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:648:72)
    at emitThree (events.js:136:13)
    at e.exports.emit (events.js:217:7)
    at u.o.on (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\bt\client.js:72:13)
    at emitTwo (events.js:126:13)
    at u.emit (events.js:214:7) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
[2:35:37 PM] finded torrent 123.1080p.MP4  and add to database
[2:35:37 PM] { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:201:16)
    at Protocol._enqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:139:13)
    at Connection.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\Connection.js:208:25)
    at Promise (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:36:14)
    at new Promise (<anonymous>)
    at Connection.e.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:22:19)
    at n (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:480:18)
    at new Promise (<anonymous>)
    at z (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:450:39)
    at L (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:619:10)
    at e.exports.<anonymous> (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:648:72)
    at emitThree (events.js:136:13)
    at e.exports.emit (events.js:217:7)
    at u.o.on (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\bt\client.js:72:13)
    at emitTwo (events.js:126:13)
    at u.emit (events.js:214:7) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
[2:35:37 PM] Rejection: { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:201:16)
    at Protocol._enqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:139:13)
    at Connection.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\Connection.js:208:25)
    at Promise (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:36:14)
    at new Promise (<anonymous>)
    at Connection.e.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:22:19)
    at n (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:480:18)
    at new Promise (<anonymous>)
    at z (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:450:39)
    at L (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:619:10)
    at e.exports.<anonymous> (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:648:72)
    at emitThree (events.js:136:13)
    at e.exports.emit (events.js:217:7)
    at u.o.on (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\bt\client.js:72:13)
    at emitTwo (events.js:126:13)
    at u.emit (events.js:214:7) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
[2:35:37 PM] Rejection: { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:201:16)
    at Protocol._enqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:139:13)
    at Connection.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\Connection.js:208:25)
    at Promise (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:36:14)
    at new Promise (<anonymous>)
    at Connection.e.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:22:19)
    at n (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:518:9)
    at new Promise (<anonymous>)
    at z (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:450:39)
    at L (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:619:10)
    at e.exports.<anonymous> (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:648:72)
    at emitThree (events.js:136:13)
    at e.exports.emit (events.js:217:7)
    at u.o.on (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\bt\client.js:72:13)
    at emitTwo (events.js:126:13)
    at u.emit (events.js:214:7) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
[2:35:42 PM] finded torrent Game.Night.2018.BDRip.1.46Gb.Dub.MegaPeer  and add to database
[2:35:42 PM] { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:201:16)
    at Protocol._enqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:139:13)
    at Connection.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\Connection.js:208:25)
    at Promise (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:36:14)
    at new Promise (<anonymous>)
    at Connection.e.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:22:19)
    at n (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:480:18)
    at new Promise (<anonymous>)
    at z (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:450:39)
    at L (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:619:10)
    at e.exports.<anonymous> (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:648:72)
    at emitThree (events.js:136:13)
    at e.exports.emit (events.js:217:7)
    at u.o.on (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\bt\client.js:72:13)
    at emitTwo (events.js:126:13)
    at u.emit (events.js:214:7) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
[2:35:42 PM] Rejection: { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:201:16)
    at Protocol._enqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:139:13)
    at Connection.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\Connection.js:208:25)
    at Promise (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:36:14)
    at new Promise (<anonymous>)
    at Connection.e.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:22:19)
    at n (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:480:18)
    at new Promise (<anonymous>)
    at z (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:450:39)
    at L (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:619:10)
    at e.exports.<anonymous> (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:648:72)
    at emitThree (events.js:136:13)
    at e.exports.emit (events.js:217:7)
    at u.o.on (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\bt\client.js:72:13)
    at emitTwo (events.js:126:13)
    at u.emit (events.js:214:7) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
[2:35:42 PM] Rejection: { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:201:16)
    at Protocol._enqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:139:13)
    at Connection.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\Connection.js:208:25)
    at Promise (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:36:14)
    at new Promise (<anonymous>)
    at Connection.e.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:22:19)
    at n (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:518:9)
    at new Promise (<anonymous>)
    at z (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:450:39)
    at L (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:619:10)
    at e.exports.<anonymous> (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:648:72)
    at emitThree (events.js:136:13)
    at e.exports.emit (events.js:217:7)
    at u.o.on (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\bt\client.js:72:13)
    at emitTwo (events.js:126:13)
    at u.emit (events.js:214:7) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
[2:35:44 PM] finded torrent S01E08.HDTV.x264-FLEET.mp4  and add to database
[2:35:44 PM] { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:201:16)
    at Protocol._enqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:139:13)
    at Connection.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\Connection.js:208:25)
    at Promise (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:36:14)
    at new Promise (<anonymous>)
    at Connection.e.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:22:19)
    at n (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:480:18)
    at new Promise (<anonymous>)
    at z (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:450:39)
    at L (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:619:10)
    at e.exports.<anonymous> (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:648:72)
    at emitThree (events.js:136:13)
    at e.exports.emit (events.js:217:7)
    at u.o.on (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\bt\client.js:72:13)
    at emitTwo (events.js:126:13)
    at u.emit (events.js:214:7) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
[2:35:44 PM] Rejection: { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:201:16)
    at Protocol._enqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:139:13)
    at Connection.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\Connection.js:208:25)
    at Promise (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:36:14)
    at new Promise (<anonymous>)
    at Connection.e.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:22:19)
    at n (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:480:18)
    at new Promise (<anonymous>)
    at z (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:450:39)
    at L (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:619:10)
    at e.exports.<anonymous> (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:648:72)
    at emitThree (events.js:136:13)
    at e.exports.emit (events.js:217:7)
    at u.o.on (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\bt\client.js:72:13)
    at emitTwo (events.js:126:13)
    at u.emit (events.js:214:7) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
[2:35:44 PM] Rejection: { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:201:16)
    at Protocol._enqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:139:13)
    at Connection.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\Connection.js:208:25)
    at Promise (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:36:14)
    at new Promise (<anonymous>)
    at Connection.e.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:22:19)
    at n (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:518:9)
    at new Promise (<anonymous>)
    at z (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:450:39)
    at L (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:619:10)
    at e.exports.<anonymous> (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:648:72)
    at emitThree (events.js:136:13)
    at e.exports.emit (events.js:217:7)
    at u.o.on (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\bt\client.js:72:13)
    at emitTwo (events.js:126:13)
    at u.emit (events.js:214:7) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
[2:35:44 PM] finded torrent 2015.BDRip.XviD.BGAUDiO-SiSO  and add to database
[2:35:44 PM] { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:201:16)
    at Protocol._enqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:139:13)
    at Connection.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\Connection.js:208:25)
    at Promise (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:36:14)
    at new Promise (<anonymous>)
    at Connection.e.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:22:19)
    at n (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:480:18)
    at new Promise (<anonymous>)
    at z (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:450:39)
    at L (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:619:10)
    at e.exports.<anonymous> (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:648:72)
    at emitThree (events.js:136:13)
    at e.exports.emit (events.js:217:7)
    at u.o.on (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\bt\client.js:72:13)
    at emitTwo (events.js:126:13)
    at u.emit (events.js:214:7) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
[2:35:44 PM] Rejection: { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:201:16)
    at Protocol._enqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:139:13)
    at Connection.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\Connection.js:208:25)
    at Promise (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:36:14)
    at new Promise (<anonymous>)
    at Connection.e.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:22:19)
    at n (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:480:18)
    at new Promise (<anonymous>)
    at z (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:450:39)
    at L (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:619:10)
    at e.exports.<anonymous> (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:648:72)
    at emitThree (events.js:136:13)
    at e.exports.emit (events.js:217:7)
    at u.o.on (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\bt\client.js:72:13)
    at emitTwo (events.js:126:13)
    at u.emit (events.js:214:7) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
[2:35:44 PM] Rejection: { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:201:16)
    at Protocol._enqueue (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\protocol\Protocol.js:139:13)
    at Connection.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\node_modules\mysql\lib\Connection.js:208:25)
    at Promise (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:36:14)
    at new Promise (<anonymous>)
    at Connection.e.query (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\mysql.js:22:19)
    at n (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:518:9)
    at new Promise (<anonymous>)
    at z (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:450:39)
    at L (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:619:10)
    at e.exports.<anonymous> (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\spider.js:648:72)
    at emitThree (events.js:136:13)
    at e.exports.emit (events.js:217:7)
    at u.o.on (C:\Users\kamal\AppData\Local\Programs\rats-search\resources\app.asar\app\webpack:\src\background\bt\client.js:72:13)
    at emitTwo (events.js:126:13)
    at u.emit (events.js:214:7) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
[2:35:45 PM] spider closing...
[2:35:45 PM] saving feed
[2:35:45 PM] sphinx closed with code 1 and signal null
`

В 2:35:45 PM завершил программу в диспетчере задач

**Comment by DEgITx** [comment]
конкретно последнее должно быть поправлено в следующей стабильной версии 0.22.1 или 0.23.0
я пока закрою эту ошибку, если возникнут новые открывай новый тикет, потому что в шапке вроде другая проблема.
