### ISSUE TITLE
[os X 10.13.3] При запуске вылетает ошибка 

### ISSUE THREAD

**Issue by lehade** [DEgITx/rats-search#8]
Uncaught Exception:
Error: bind EADDRINUSE 0.0.0.0:4446
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at _handle.lookup (dgram.js:215:18)
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:431:7)
    at startup (bootstrap_node.js:155:9)
    at bootstrap_node.js:551:3

**Comment by DEgITx** [comment]
4446 порт для чего-то уже используется, проверьте

**Comment by lehade** [comment]
Cнес все лишнее, ошибка повторяется.
TCP 10.8.0.6:56774->213.180.204.106:443 (ESTABLISHED)
TCP 10.0.0.11:56274->10.0.0.100:80 (ESTABLISHED)
TCP 10.0.0.11:58110->10.0.0.100:80 (ESTABLISHED)
TCP 10.0.0.11:57334->192.30.253.124:443 (ESTABLISHED)
TCP 10.0.0.11:57334->192.30.253.124:443 (ESTABLISHED)
TCP *:9312 (LISTEN)
TCP *:9306 (LISTEN)
TCP *:57502 (LISTEN)
TCP 10.0.0.11:57502->10.0.0.14:52910 (ESTABLISHED)
UDP *:3722 

И сама программа не стартует.

**Comment by DEgITx** [comment]
Ну ошибка явно в порте или в правах запуска, изза чего может нерезервировать порт

**Comment by lehade** [comment]
Есть возможность перекинуть порт не запуская программу ? :)

**Comment by DEgITx** [comment]
Хорошо, это уже другой тикет тогда
