### ISSUE TITLE
Attempt to install the server on Linux CentOS 6

### ISSUE THREAD

**Issue by slrslr** [DEgITx/rats-search#88]
Hello, the installation process did not take 3 commands like in README.md, but like 30 :-) and ended up in blank page at 8095, can you please take a look and give advice? 

"Git clone" commands failed:

```
# git clone git@github.com:DEgITx/rats-search.git
Initialized empty Git repository in /root/rats-search/.git/
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

# git clone https://github.com/DEgITx/rats-search.git
Initialized empty Git repository in /root/rats/rats-search/.git/
error:  while accessing https://github.com/DEgITx/rats-search.git/info/refs

fatal: HTTP request failed
```

I found an advice to update and install following (i am using yum package installer as i am on CentOS, othervise one use apt-get):

`# yum update -y nss curl libcurl;yum install ca-certificates`

Then one "git clone" continue to fail:"
```
# git clone git@github.com:DEgITx/rats-search.git
Initialized empty Git repository in /root/rats-search/.git/
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
```

but other started working!:
```
# git clone https://github.com/DEgITx/rats-search.git
Initialized empty Git repository in /root/rats-search/.git/
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 4963 (delta 16), reused 24 (delta 11), pack-reused 4929
Receiving objects: 100% (4963/4963), 43.31 MiB | 796 KiB/s, done.
Resolving deltas: 100% (3187/3187), done.
```

Then i tried:
```
# cd rats*
# npm install
npm http GET https://registry.npmjs.org/cheerio
npm http GET https://registry.npmjs.org/compare-versions
...
npm http GET https://registry.npmjs.org/electron-updater
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1430:32)
npm ERR!     at SecurePair.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:1029:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:521:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:341:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:418:25)
npm ERR!     at doWrite (_stream_writable.js:226:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:216:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
npm ERR!     at write (_stream_readable.js:602:24)
npm ERR!     at flow (_stream_readable.js:611:7)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-042stab093.5
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /root/rats-search
npm ERR! node -v v0.10.48
npm ERR! npm -v 1.3.6
npm http GET https://registry.npmjs.org/fs-jetpack
npm http GET https://registry.npmjs.org/ansi-256-colors
...
npm http GET https://registry.npmjs.org/webtorrent
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/rats-search/npm-debug.log
npm ERR! not ok code 0
```

i read that the error CERT_UNTRUSTED can be prevented by command "npm config set strict-ssl false" or by upgrading node.js, i selected later running following commands on my CentOS Linux:
```
yum install -y gcc-c++ make
curl -sL https://rpm.nodesource.com/setup_10.x | sudo -E bash -
sudo yum install nodejs
```

and then making sure i am in git clonned rats folder (# cd rats*)
`# npm install`

resulting in:
```
npm WARN lifecycle rats-search@1.1.4~postinstall: cannot run in wd rats-search@1.1.4 electron-builder install-app-deps (wd=/root/rats-search)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

"npm audit fix" resulted in:
```
npm WARN @semantic-release/changelog@1.1.1 requires a peer of semantic-release@>=13.3.0 <15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/exec@2.3.0 requires a peer of semantic-release@>=13.0.0 <16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/git@3.1.1 requires a peer of semantic-release@>=13.3.0 <15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

\# npm run buildweb

```
> rats-search@1.1.4 buildweb /root/rats-search
> node src/background/webpack.js

succesfully builded web version
```

\# npm run server

```
> rats-search@1.1.4 server /root/rats-search
> node src/background/server.js

[system] Rats v1.1.4
[system] Listening web server on 8095 port
[system] Platform: linux
[system] Arch: x64
[system] OS Release: 2.6.32-042stab093.5
[system] CPU: Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
[system] CPU Logic cores: 4
[system] Total memory: 1024.00 MB
[system] Free memory: 148.39 MB
[system] NodeJS: v10.15.3
[sphinx] Sphinx Path: /root/rats-search/imports/linux/x64/searchd
(node:8909) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[udp-tracker] listening udp tracker respose on 0.0.0.0:4446
[sphinx] writed sphinx config to /root/rats-search
[sphinx] db path: /root/rats-search
[sphinx] sphinx closed with code 1 and signal null
```

and the web console at port 8095 shows blank page..

**Comment by DEgITx** [comment]
Seems like one of precompiled component not started for some reason under centos (will recheck, and will place compatible one soon)

**Comment by slrslr** [comment]
I interrupted the session and [here is](https://pastebin.com/F9FTmrA1) the runtime log file if it can be anyhow useful to You.

**Comment by DEgITx** [comment]
https://github.com/DEgITx/rats-search/blob/master/docs/SERVER_COMPATIBILITY.md
I described how to fix start

**Comment by slrslr** [comment]
i ran that and it downloaded RPMs and also output:
`warning: glibc-2.17-55.el6.x86_64.rpm: Header V3 RSA/SHA1 Signature, key ID 73ec361c: NOKEY
error: Failed dependencies:
        glibc-common = 2.12-1.166.el6_7.3 is needed by (installed) glibc-2.12-1.166.el6_7.3.i686`

so i tried to run "yum install glibc-common", it updated:
```
  glibc-common.x86_64 0:2.12-1.212.el6
Dependency Updated:
  glibc.i686 0:2.12-1.212.el6      glibc.x86_64 0:2.12-1.212.el6      glibc-devel.x86_64 0:2.12-1.212.el6      glibc-headers.x86_64 0:2.12-1.212.el6      nscd.x86_64 0:2.12-1.212.el6
```
then i go to downloaded rats directory and ran "npm run server", result:
```
...
(node:18174) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[udp-tracker] listening udp tracker respose on 0.0.0.0:4446
[sphinx] writed sphinx config to /root/rats-search
[sphinx] db path: /root/rats-search
[sphinx] sphinx closed with code 1 and signal null
```
i checked web browser at port 8095, it is loading a few seconds, then end up showing empty page. After terminating the runtime by Ctrl+C the log file is [here](https://pastebin.com/nQjXSeZG)

**Comment by DEgITx** [comment]
"yum install glibc-common" installed too old version (2.12), as said in the topic 2.17 required.
So can you check is you can clear/delete "glibc-2.12-1.166.el6_7.3.i686" packet (in the case you on 64-bit centos it must be safe)
if there no other installed packets depends on it than clear it, and try script again, it must install new glibc without errors without this packet

**Comment by slrslr** [comment]
>  clear/delete "glibc-2.12-1.166.el6_7.3.i686" packet

i do not know how, if you know, let me know the command. yes i have 64bit

after that, i am unsure why i should try the script again, i already did, did you modified it?

**Comment by DEgITx** [comment]
> yum remove glibc-2.12-1.166.el6_7.3.i686
and make sure it not delete anything else that needed, after that retry command, last time because of this packet it not finish it work - thats why you should try again.

**Comment by slrslr** [comment]
thx, that command NOT worked:
`No Match for argument: glibc-2.12-1.166.el6_7.3.i686`

\# yum list|grep glibc
```
glibc.i686                                2.12-1.212.el6               @base
glibc.x86_64                              2.12-1.212.el6               @base
glibc-common.x86_64                       2.12-1.212.el6               @base
glibc-devel.x86_64                        2.12-1.212.el6               @base
glibc-headers.x86_64                      2.12-1.212.el6               @base
vzdummy-glibc.noarch                      2.12-1.7.el6                 installed
compat-glibc.x86_64                       1:2.5-46.2                   base
compat-glibc-headers.x86_64               1:2.5-46.2                   base
glibc-devel.i686                          2.12-1.212.el6               base
glibc-static.i686                         2.12-1.212.el6               base
glibc-static.x86_64                       2.12-1.212.el6               base
glibc-utils.x86_64                        2.12-1.212.el6               base
```
I tried to "yum remove glibc.i686" instead, but that wanted to uninstall many dependencies so i found i can use: rpm -e --nodeps "namehere"

\# rpm -qa | grep "glibc"
```
glibc-2.12-1.212.el6.x86_64
glibc-common-2.12-1.212.el6.x86_64
glibc-devel-2.12-1.212.el6.x86_64
glibc-headers-2.12-1.212.el6.x86_64
glibc-2.12-1.212.el6.i686
vzdummy-glibc-2.12-1.7.el6.noarch
```
Please which namehere i should use (from rpm -qa command output above)?

I tried to remove first one, but ended up like this:

```
# rpm -e --nodeps glibc-2.12-1.212.el6.x86_64
warning: %postun(glibc-2.12-1.212.el6.x86_64) scriptlet failed, exit status 127

# rpm -qa | grep "glibc"
-bash: /bin/grep: /lib64/ld-linux-x86-64.so.2: bad ELF interpreter: No such file or directory
-bash: /bin/rpm: /lib64/ld-linux-x86-64.so.2: bad ELF interpreter: No such file or directory
```
yum, wget, rpm does not work. for example yum says "-bash: /usr/bin/yum: /usr/bin/python: bad interpreter: No such file or directory"

I have access to the file system, do you have an idea about the fix? Which files/directories can be missing?

**Comment by DEgITx** [comment]
why do you touch "glibc-2.12-1.212.el6.x86_64"? x86_64 glibc only can be UPDATED (never be DELETED), only packages ended with glibc i686 can be safetly deleted on 64-bit system.
delete of "glibc-2.12-1.212.el6.x86_64" is very dangerous, system can be corrupted, and commands can not respond after that

try to restore this packet, nothing good to advice here how to restore it, try it by yourself:
https://serverfault.com/questions/623497/all-commands-stopped-working-in-centos-6-5

**Comment by DEgITx** [comment]
to make it more simple, after you recover glibc x86_64 to normal state, here the modifcated script for update, after you recover your glibc

[glibc-2.17_centos6_nodeps.sh.zip](https://github.com/DEgITx/rats-search/files/3022065/glibc-2.17_centos6_nodeps.sh.zip)

**Comment by slrslr** [comment]
update: i fixed that by copying files from /lib64/ of the working CentOS 6 installation to the not working one. Please so which package i need to remove using rpm -e --nodeps ? And then i will run Your wget command to install new version ? thank you very much for patience

**Comment by DEgITx** [comment]
just try update one glibc-2.17_centos6_nodeps.sh.zip that I attached, unpack, that
> chmod +x glibc-2.17_centos6_nodeps.sh
> ./glibc-2.17_centos6_nodeps.sh
as root

**Comment by slrslr** [comment]
update: i fixed that by copying files from /lib64/ of the working CentOS 6 installation to the not working one. I then tried to run script inside yours provided .zip archive and result is:
`        file /etc/nsswitch.conf from install of glibc-2.17-55.el6.x86_64 conflicts with file from package glibc-2.12-1.212.el6.i686
        file /etc/rpc from install of glibc-2.17-55.el6.x86_64 conflicts with file from package glibc-2.12-1.212.el6.i686`

**Comment by DEgITx** [comment]
[glibc-2.17_centos6__all.sh.zip](https://github.com/DEgITx/rats-search/files/3022138/glibc-2.17_centos6__all.sh.zip)
try this one :) I included additional packages, probably now must be ok

**Comment by slrslr** [comment]
thx) i wget it into new directory not to make issues with old files and ran it (bash glibc-2.17_centos6__all.sh). Result:
```
error: Failed dependencies:
        glibc = 2.12-1.212.el6 is needed by (installed) nscd-2.12-1.212.el6.x86_64
```
(note i can not yet use yum as it is buggy atm, only rpm)

\# rpm -qa|grep nscd
`nscd-2.12-1.212.el6.x86_64`

after i removed it:
`rpm -e --nodeps nscd-2.12-1.212.el6.x86_64`

and ran your script again:
```warning: glibc-2.17-55.el6.x86_64.rpm: Header V3 RSA/SHA1 Signature, key ID 73ec361c: NOKEY
Preparing...                ########################################### [100%]
        file /usr/bin/ldd conflicts between attempted installs of glibc-common-2.17-55.el6.i686 and glibc-common-2.17-55.el6.x86_64
        file /usr/lib/locale/locale-archive.tmpl conflicts between attempted installs of glibc-common-2.17-55.el6.i686 and glibc-common-2.17-55.el6.x86_64
```

**Comment by DEgITx** [comment]
[glibc-2.17_centos6__all.sh.zip](https://github.com/DEgITx/rats-search/files/3022212/glibc-2.17_centos6__all.sh.zip)
try this one (I removed conflicted one from script)

**Comment by DEgITx** [comment]
[glibc-2.17_centos6__all.sh.zip](https://github.com/DEgITx/rats-search/files/3022215/glibc-2.17_centos6__all.sh.zip)

**Comment by slrslr** [comment]
i ended up using the first one. during rpm installation i seen some errors possibly related to my bad command "rpm -e --nodeps glibc-2.12-1.212.el6.x86_64":

```
warning: glibc-2.17-55.el6.x86_64.rpm: Header V3 RSA/SHA1 Signature, key ID 73ec361c: NOKEY
Preparing...                ########################################### [100%]
   1:glibc-common           ########################################### [ 20%]
/usr/sbin/build-locale-archive: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/sbin/build-locale-archive)
/usr/sbin/build-locale-archive: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/sbin/build-locale-archive)
   2:glibc                  ########################################### [ 40%]
/sbin/ldconfig: /lib64/libcgroup.so.1 is not a symbolic link

   3:glibc-headers          ########################################### [ 60%]
   4:glibc-devel            ########################################### [ 80%]
   5:glibc                  warning: /etc/nsswitch.conf created as /etc/nsswitch.conf.rpmnew
warning: /etc/rpc created as /etc/rpc.rpmnew
########################################### [100%]
/sbin/ldconfig: /lib64/libcgroup.so.1 is not a symbolic link

/sbin/ldconfig: /lib64/libcgroup.so.1 is not a symbolic link
```

wondering if i should somehow first install again that old glibc which i removed and caused issues. And then after that execute your script. yum continue not working properly - upon asking if it should update some packages it ends with error "AttributeError: 'YumConf' object has no attribute 'assumeno'")

**Comment by DEgITx** [comment]
> /usr/sbin/build-locale-archive: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/sbin/build-locale-archive)
this is ok during installation, I saw yesterday on testing centos yesterday when tried.

just try to run some commands to make shure all works, and now probably you will be abble to run rats

**Comment by slrslr** [comment]
After i restored the system from backup, i tried to ran the wget command mentioned at https://github.com/DEgITx/rats-search/blob/master/docs/SERVER_COMPATIBILITY.md

it failed:
`error: Failed dependencies:
        glibc-common = 2.12-1.166.el6_7.3 is needed by (installed) glibc-2.12-1.166.el6_7.3.i686
`

So i ran Yours modified version: https://github.com/DEgITx/rats-search/files/3022215/glibc-2.17_centos6__all.sh.zip

result is:
`warning: glibc-2.17-55.el6.x86_64.rpm: Header V3 RSA/SHA1 Signature, key ID 73ec361c: NOKEY
error: Failed dependencies:
        glibc = 2.12-1.166.el6_7.3 is needed by (installed) nscd-2.12-1.166.el6_7.3.x86_64
`
how to continue?

**Comment by javaaiorg** [comment]
You can use independent sphinx to fix this error: 
https://www.javaai.org/a/c892d1e98fd94a64018ff4702e4c000a

**Comment by kotenok2000** [comment]
Nice necropost.
