### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by Polve** [DEgITx/rats-search#97]
After a few minutes of running with "npm run server" I get the following crash:

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rats-search@1.3.0 server: `node src/background/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rats-search@1.3.0 server script.

**Comment by DEgITx** [comment]
which node js version do you use? can you send me full rats.log?

**Comment by DEgITx** [comment]
must be closed
